// Auto-generated by scripts/fonts/build-fonts.ts
// Do not edit this file directly. Run `bun run build:fonts` to regenerate.
// Nerd Fonts v3.4.0
import type { FontManifestEntry } from './types';

export const FONT_MANIFEST: FontManifestEntry[] = [
  {
    id: "geist-mono",
    displayName: "Geist Mono",
    cssFamily: "GeistMonoTmex",
    bundled: true,
    isDefault: true,
    files: { regular: "/fonts/GeistMonoNerdFontMono-Regular.woff2", bold: "/fonts/GeistMonoNerdFontMono-Bold.woff2" },
  },
  {
    id: "jetbrains-mono",
    displayName: "JetBrains Mono",
    cssFamily: "JetBrainsMonoTmex",
    bundled: true,
    files: { regular: "/fonts/generated/jetbrains-mono/jetbrains-mono-regular.woff2", bold: "/fonts/generated/jetbrains-mono/jetbrains-mono-bold.woff2" },
  },
  {
    id: "fira-code",
    displayName: "Fira Code",
    cssFamily: "FiraCodeTmex",
    bundled: true,
    files: { regular: "/fonts/generated/fira-code/fira-code-regular.woff2", bold: "/fonts/generated/fira-code/fira-code-bold.woff2" },
  },
  {
    id: "blex-mono",
    displayName: "Blex Mono (IBM Plex Mono)",
    cssFamily: "BlexMonoTmex",
    bundled: true,
    files: { regular: "/fonts/generated/blex-mono/blex-mono-regular.woff2", bold: "/fonts/generated/blex-mono/blex-mono-bold.woff2" },
  },
  {
    id: "noto-sans-mono",
    displayName: "Noto Sans Mono",
    cssFamily: "NotoSansMTmex",
    bundled: true,
    files: { regular: "/fonts/generated/noto-sans-mono/noto-sans-mono-regular.woff2", bold: "/fonts/generated/noto-sans-mono/noto-sans-mono-bold.woff2" },
  },
  {
    id: "zed-mono",
    displayName: "Zed Mono",
    cssFamily: "ZedMonoTmex",
    bundled: true,
    files: { regular: "/fonts/generated/zed-mono/zed-mono-regular.woff2", bold: "/fonts/generated/zed-mono/zed-mono-bold.woff2" },
  },
  {
    id: "victor-mono",
    displayName: "Victor Mono",
    cssFamily: "VictorMonoTmex",
    bundled: true,
    files: { regular: "/fonts/generated/victor-mono/victor-mono-regular.woff2", bold: "/fonts/generated/victor-mono/victor-mono-bold.woff2" },
  },
];

export const DEFAULT_FONT_ID = "geist-mono";
