// WebSocket Borsh 协议模块
// 参考: docs/ws-protocol/2026021402-ws-borsh-v1-spec.md

// 重新导出 zorsh b 命名空间供类型使用
export { b } from '@zorsh/zorsh';

// ========== Kind 常量 ==========
export {
  KIND_HELLO_C2S,
  KIND_HELLO_S2C,
  KIND_PING,
  KIND_PONG,
  KIND_ERROR,
  KIND_DEVICE_CONNECT,
  KIND_DEVICE_CONNECTED,
  KIND_DEVICE_DISCONNECT,
  KIND_DEVICE_DISCONNECTED,
  KIND_DEVICE_EVENT,
  KIND_TMUX_SELECT,
  KIND_TMUX_SELECT_WINDOW,
  KIND_TMUX_CREATE_WINDOW,
  KIND_TMUX_CLOSE_WINDOW,
  KIND_TMUX_CLOSE_PANE,
  KIND_TMUX_RENAME_WINDOW,
  KIND_TMUX_EVENT,
  KIND_STATE_SNAPSHOT,
  KIND_STATE_SNAPSHOT_DIFF,
  KIND_TMUX_SET_WINDOW_STYLE,
  KIND_TMUX_REORDER_WINDOWS,
  KIND_TMUX_REORDER_PANES,
  KIND_TMUX_SUBSCRIBE_PANES,
  KIND_TMUX_FETCH_PANE_HISTORY,
  KIND_TMUX_RESIZE_PANE,
  KIND_TMUX_APPLY_STACKED_LAYOUT,
  KIND_TMUX_SPLIT_PANE,
  KIND_TMUX_FOCUS_PANE,
  KIND_TMUX_RENAME_PANE,
  KIND_TMUX_MOVE_PANE,
  KIND_TMUX_BREAK_PANE,
  KIND_TMUX_WINDOW_CREATED,
  KIND_TERM_INPUT,
  KIND_TERM_PASTE,
  KIND_TERM_RESIZE,
  KIND_TERM_SYNC_SIZE,
  KIND_TERM_OUTPUT,
  KIND_TERM_HISTORY,
  KIND_CLIPBOARD_WRITE,
  KIND_TERM_KEY_INPUT,
  KIND_SWITCH_ACK,
  KIND_LIVE_RESUME,
  KIND_CHUNK,
  KIND_AGENT_SUBSCRIBE,
  KIND_AGENT_UNSUBSCRIBE,
  KIND_AGENT_EVENT,
  KIND_WATCH_EVENT,
  KIND_SITE_THEME_UPDATE,
  KIND_SETTINGS_UPDATE,
  KIND_NOTIFY_EVENT,
  KIND_CANONICAL_COMMAND,
  KIND_CANONICAL_EVENT,
  isValidKind,
  kindToString,
} from './kind';

export {
  CANONICAL_STATE_PROTOCOL_VERSION,
  CANONICAL_STATE_MAX_FRAME_BYTES,
  CANONICAL_STATE_MAX_PAYLOAD_BYTES,
  WS_ENVELOPE_WIRE_OVERHEAD_BYTES,
  TERMINAL_KEY_MOD_SHIFT,
  TERMINAL_KEY_MOD_ALT,
  TERMINAL_KEY_MOD_CTRL,
  TERMINAL_KEY_MOD_SUPER,
  TERMINAL_KEY_MOD_HYPER,
  TERMINAL_KEY_MOD_META,
  TERMINAL_KEY_MOD_CAPS_LOCK,
  TERMINAL_KEY_MOD_NUM_LOCK,
  TERMINAL_KEY_MOD_MASK,
  SOURCE_ENTITY_DEVICE,
  SOURCE_ENTITY_SERVER,
  SOURCE_ENTITY_SESSION,
  SOURCE_ENTITY_WINDOW,
  SOURCE_ENTITY_PANE,
  SOURCE_FIELD_NAME,
  SOURCE_FIELD_TITLE,
  SOURCE_FIELD_INDEX,
  SOURCE_FIELD_ACTIVE,
  SOURCE_FIELD_LAYOUT,
  SOURCE_FIELD_WIDTH,
  SOURCE_FIELD_HEIGHT,
  SOURCE_FIELD_LEFT,
  SOURCE_FIELD_TOP,
  SOURCE_FIELD_CURRENT_PATH,
  SOURCE_FIELD_CURRENT_COMMAND,
  SOURCE_FIELD_CONNECTED,
  SOURCE_FIELD_PANE_EPOCH,
  SOURCE_FIELD_CUSTOM_NAME,
  SUBSCRIPTION_REJECTED_NOT_FOUND,
  SUBSCRIPTION_REJECTED_RESOURCE_EXHAUSTED,
  SUBSCRIPTION_REJECTED_EPOCH_CHANGED,
  SOURCE_GAP_SCOPE_STREAM,
  SOURCE_GAP_SCOPE_METADATA,
  SOURCE_GAP_SCOPE_PANE,
  SOURCE_GAP_REASON_METADATA_GAP,
  SOURCE_GAP_REASON_PANE_GAP,
  SOURCE_GAP_REASON_EPOCH_CHANGED,
  SOURCE_GAP_REASON_CACHE_EVICTED,
  SOURCE_GAP_REASON_RESOURCE_EXHAUSTED,
  type SourceEntityKey,
  type SourceMetadataValue,
  type SourceMetadataField,
  type SourceMetadataRecord,
  type CanonicalPaneTarget,
  type CanonicalTerminalCursor,
  type CanonicalHistoryCursor,
  type CanonicalPaneSubscription,
  type TerminalKey,
  type TerminalKeyAction,
  type CanonicalTerminalKeyInput,
  type CanonicalCommand,
  type CanonicalCommandEnvelope,
  type CanonicalEvent,
  type CanonicalEventEnvelope,
  assertCanonicalPayloadBounded,
  encodeCanonicalCommandPayload,
  decodeCanonicalCommandPayload,
  encodeCanonicalEventPayload,
  decodeCanonicalEventPayload,
} from './canonical-state';
export {
  STATE_SNAPSHOT_DIFF_FORMAT_ABSOLUTE_JSON,
  applyLegacyStateSnapshotDiff,
  decodeLegacyStateSnapshotDiff,
  encodeLegacyStateSnapshotDiff,
  sourceMetadataPatchToLegacyDiff,
  type LegacyMetadataEntityDiff,
  type LegacyMetadataFieldValue,
  type LegacyStateSnapshotDiff,
} from './state-snapshot-diff';

// ========== 站点主题枚举值 ==========
export {
  SITE_THEME_DARK,
  SITE_THEME_LIGHT,
} from './schema';

// ========== Agent/Watch 事件常量与 payload 类型 ==========
export {
  AGENT_EVENT_SYNC,
  AGENT_EVENT_STATUS,
  AGENT_EVENT_TEXT_DELTA,
  AGENT_EVENT_REASONING_DELTA,
  AGENT_EVENT_TOOL_CALL,
  AGENT_EVENT_TOOL_RESULT,
  AGENT_EVENT_CONFIRMATION_REQUEST,
  AGENT_EVENT_CONFIRMATION_RESOLVED,
  AGENT_EVENT_MESSAGE_PERSISTED,
  AGENT_EVENT_ERROR,
  AGENT_EVENT_TURN_FINISHED,
  AGENT_EVENT_CREDENTIAL_WARNING,
  AGENT_EVENT_QUEUE_UPDATED,
  WATCH_EVENT_TRIGGERED,
  WATCH_EVENT_MODEL_UNAVAILABLE,
  WATCH_EVENT_RULE_ERROR,
  type AgentSessionWireStatus,
  type AgentConfirmationWireStatus,
  type AgentPendingConfirmation,
  type AgentQueuedMessageWire,
  type AgentQueueUpdatedPayload,
  type AgentSyncEventPayload,
  type AgentStatusEventPayload,
  type AgentTextDeltaPayload,
  type AgentReasoningDeltaPayload,
  type AgentToolCallPayload,
  type AgentToolResultPayload,
  type AgentConfirmationRequestPayload,
  type AgentConfirmationResolvedPayload,
  type AgentMessagePersistedPayload,
  type AgentErrorEventPayload,
  type AgentTurnFinishedPayload,
  type AgentCredentialWarningPayload,
  type WatchTriggeredPayload,
  type WatchModelUnavailablePayload,
  type WatchRuleErrorPayload,
  type AgentEventPayloadMap,
  type WatchEventPayloadMap,
  type AgentEventType,
  type WatchEventType,
} from './agent';

// ========== 错误码 ==========
export {
  ERROR_UNSUPPORTED_PROTOCOL,
  ERROR_INVALID_FRAME,
  ERROR_UNKNOWN_KIND,
  ERROR_PAYLOAD_DECODE_FAILED,
  ERROR_FRAME_TOO_LARGE,
  ERROR_DEVICE_NOT_FOUND,
  ERROR_DEVICE_CONNECT_FAILED,
  ERROR_TMUX_TARGET_NOT_FOUND,
  ERROR_TMUX_NOT_READY,
  ERROR_SELECT_CONFLICT,
  ERROR_SELECT_TOKEN_MISMATCH,
  ERROR_INTERNAL_ERROR,
  ERROR_MESSAGES,
  getErrorMessage,
  WsBorshError,
} from './errors';

// ========== Schema ==========
export * as schema from './schema';

// ========== pane 终端模式位图 ==========
export {
  PANE_MODE_MOUSE_STANDARD,
  PANE_MODE_MOUSE_BUTTON,
  PANE_MODE_MOUSE_ALL,
  PANE_MODE_MOUSE_SGR,
  PANE_MODE_MOUSE_UTF8,
  PANE_MODE_ALT_SCREEN,
  PANE_MODE_FLAGS_PRESENT,
  EMPTY_PANE_MODE_FLAGS,
  type PaneModeFlags,
  encodePaneModes,
  decodePaneModes,
} from './pane-modes';

// ========== 编解码器 ==========
export {
  MAGIC,
  CURRENT_VERSION,
  DEFAULT_MAX_FRAME_BYTES,
  FLAG_ACK_REQUIRED,
  FLAG_IS_ACK,
  FLAG_IS_ERROR,
  FLAG_IS_CHUNK,
  FLAG_IS_COMPRESSED,
  type Envelope,
  type DecodedEnvelope,
  encodeEnvelope,
  encodePayload,
  decodeEnvelope,
  decodePayload,
  decodeEnvelopeAndPayload,
  type ChunkData,
  encodeChunk,
  decodeChunk,
  hasFlag,
  setFlag,
  checkMagic,
  createSeqGenerator,
} from './codec';

// ========== 分片 ==========
export {
  CHUNK_TIMEOUT_MS,
  MAX_CHUNK_STREAMS,
  MAX_CHUNKS_PER_MESSAGE,
  type Chunk,
  type ReassembledMessage,
  type ChunkReassemblerOptions,
  ChunkReassembler,
  type ChunkOptions,
  type ChunkedResult,
  splitPayloadIntoChunks,
  generateChunkStreamId,
  resetChunkStreamId,
} from './chunk';

// ========== 转换层 ==========
export {
  encodeDeviceEventPayload,
  encodeTmuxEventPayload,
  encodeStateSnapshot,
  decodeDeviceEventPayload,
  decodeTmuxEventPayload,
  decodeStateSnapshot,
} from './convert';
