// WebSocket Borsh 协议 Kind 常量定义
// 参考: docs/ws-protocol/2026021402-ws-borsh-v1-spec.md

// ========== 会话/协商 (0x0001-0x00FF) ==========
export const KIND_HELLO_C2S = 0x0001;
export const KIND_HELLO_S2C = 0x0002;
export const KIND_PING = 0x0003;
export const KIND_PONG = 0x0004;
export const KIND_ERROR = 0x0005;

// ========== 设备连接 (0x0100-0x01FF) ==========
export const KIND_DEVICE_CONNECT = 0x0101;
export const KIND_DEVICE_CONNECTED = 0x0102;
export const KIND_DEVICE_DISCONNECT = 0x0103;
export const KIND_DEVICE_DISCONNECTED = 0x0104;
export const KIND_DEVICE_EVENT = 0x0105;

// ========== tmux 控制 (0x0200-0x02FF) ==========
export const KIND_TMUX_SELECT = 0x0201;
export const KIND_TMUX_SELECT_WINDOW = 0x0202;
export const KIND_TMUX_CREATE_WINDOW = 0x0203;
export const KIND_TMUX_CLOSE_WINDOW = 0x0204;
export const KIND_TMUX_CLOSE_PANE = 0x0205;
export const KIND_TMUX_RENAME_WINDOW = 0x0206;
export const KIND_TMUX_EVENT = 0x0207;
export const KIND_STATE_SNAPSHOT = 0x0208;
export const KIND_STATE_SNAPSHOT_DIFF = 0x0209;
export const KIND_TMUX_SET_WINDOW_STYLE = 0x020a;
export const KIND_TMUX_REORDER_WINDOWS = 0x020b;
export const KIND_TMUX_REORDER_PANES = 0x020c;
// ---------- 分屏（split screen） ----------
export const KIND_TMUX_SUBSCRIBE_PANES = 0x020d;
export const KIND_TMUX_FETCH_PANE_HISTORY = 0x020e;
export const KIND_TMUX_RESIZE_PANE = 0x020f;
export const KIND_TMUX_APPLY_STACKED_LAYOUT = 0x0210;
export const KIND_TMUX_SPLIT_PANE = 0x0211;
export const KIND_TMUX_FOCUS_PANE = 0x0212;
export const KIND_TMUX_RENAME_PANE = 0x0213;
export const KIND_TMUX_MOVE_PANE = 0x0214;
export const KIND_TMUX_BREAK_PANE = 0x0215;

// ========== 终端数据 (0x0300-0x03FF) ==========
export const KIND_TERM_INPUT = 0x0301;
export const KIND_TERM_PASTE = 0x0302;
export const KIND_TERM_RESIZE = 0x0303;
export const KIND_TERM_SYNC_SIZE = 0x0304;
export const KIND_TERM_OUTPUT = 0x0305;
export const KIND_TERM_HISTORY = 0x0306;
export const KIND_CLIPBOARD_WRITE = 0x0307;

// ========== 切换屏障 (0x0400-0x04FF) ==========
export const KIND_SWITCH_ACK = 0x0401;
export const KIND_LIVE_RESUME = 0x0402;

// ========== 分片 (0x0500-0x05FF) ==========
export const KIND_CHUNK = 0x0501;

// ========== Agent (0x0600-0x06FF) ==========
export const KIND_AGENT_SUBSCRIBE = 0x0601;
export const KIND_AGENT_UNSUBSCRIBE = 0x0602;
export const KIND_AGENT_EVENT = 0x0603;

// ========== Watch (0x0700-0x07FF) ==========
export const KIND_WATCH_EVENT = 0x0701;

// ========== Kind 有效性检查 ==========
const VALID_KINDS = new Set<number>([
  KIND_HELLO_C2S,
  KIND_HELLO_S2C,
  KIND_PING,
  KIND_PONG,
  KIND_ERROR,
  KIND_DEVICE_CONNECT,
  KIND_DEVICE_CONNECTED,
  KIND_DEVICE_DISCONNECT,
  KIND_DEVICE_DISCONNECTED,
  KIND_DEVICE_EVENT,
  KIND_TMUX_SELECT,
  KIND_TMUX_SELECT_WINDOW,
  KIND_TMUX_CREATE_WINDOW,
  KIND_TMUX_CLOSE_WINDOW,
  KIND_TMUX_CLOSE_PANE,
  KIND_TMUX_RENAME_WINDOW,
  KIND_TMUX_EVENT,
  KIND_STATE_SNAPSHOT,
  KIND_STATE_SNAPSHOT_DIFF,
  KIND_TMUX_SET_WINDOW_STYLE,
  KIND_TMUX_REORDER_WINDOWS,
  KIND_TMUX_REORDER_PANES,
  KIND_TMUX_SUBSCRIBE_PANES,
  KIND_TMUX_FETCH_PANE_HISTORY,
  KIND_TMUX_RESIZE_PANE,
  KIND_TMUX_APPLY_STACKED_LAYOUT,
  KIND_TMUX_SPLIT_PANE,
  KIND_TMUX_FOCUS_PANE,
  KIND_TMUX_RENAME_PANE,
  KIND_TMUX_MOVE_PANE,
  KIND_TMUX_BREAK_PANE,
  KIND_TERM_INPUT,
  KIND_TERM_PASTE,
  KIND_TERM_RESIZE,
  KIND_TERM_SYNC_SIZE,
  KIND_TERM_OUTPUT,
  KIND_TERM_HISTORY,
  KIND_CLIPBOARD_WRITE,
  KIND_SWITCH_ACK,
  KIND_LIVE_RESUME,
  KIND_CHUNK,
  KIND_AGENT_SUBSCRIBE,
  KIND_AGENT_UNSUBSCRIBE,
  KIND_AGENT_EVENT,
  KIND_WATCH_EVENT,
]);

export function isValidKind(kind: number): boolean {
  return VALID_KINDS.has(kind);
}

export function kindToString(kind: number): string {
  const kindMap: Record<number, string> = {
    [KIND_HELLO_C2S]: 'HELLO_C2S',
    [KIND_HELLO_S2C]: 'HELLO_S2C',
    [KIND_PING]: 'PING',
    [KIND_PONG]: 'PONG',
    [KIND_ERROR]: 'ERROR',
    [KIND_DEVICE_CONNECT]: 'DEVICE_CONNECT',
    [KIND_DEVICE_CONNECTED]: 'DEVICE_CONNECTED',
    [KIND_DEVICE_DISCONNECT]: 'DEVICE_DISCONNECT',
    [KIND_DEVICE_DISCONNECTED]: 'DEVICE_DISCONNECTED',
    [KIND_DEVICE_EVENT]: 'DEVICE_EVENT',
    [KIND_TMUX_SELECT]: 'TMUX_SELECT',
    [KIND_TMUX_SELECT_WINDOW]: 'TMUX_SELECT_WINDOW',
    [KIND_TMUX_CREATE_WINDOW]: 'TMUX_CREATE_WINDOW',
    [KIND_TMUX_CLOSE_WINDOW]: 'TMUX_CLOSE_WINDOW',
    [KIND_TMUX_CLOSE_PANE]: 'TMUX_CLOSE_PANE',
    [KIND_TMUX_RENAME_WINDOW]: 'TMUX_RENAME_WINDOW',
    [KIND_TMUX_EVENT]: 'TMUX_EVENT',
    [KIND_STATE_SNAPSHOT]: 'STATE_SNAPSHOT',
    [KIND_STATE_SNAPSHOT_DIFF]: 'STATE_SNAPSHOT_DIFF',
    [KIND_TMUX_SET_WINDOW_STYLE]: 'TMUX_SET_WINDOW_STYLE',
    [KIND_TMUX_REORDER_WINDOWS]: 'TMUX_REORDER_WINDOWS',
    [KIND_TMUX_REORDER_PANES]: 'TMUX_REORDER_PANES',
    [KIND_TMUX_SUBSCRIBE_PANES]: 'TMUX_SUBSCRIBE_PANES',
    [KIND_TMUX_FETCH_PANE_HISTORY]: 'TMUX_FETCH_PANE_HISTORY',
    [KIND_TMUX_RESIZE_PANE]: 'TMUX_RESIZE_PANE',
    [KIND_TMUX_APPLY_STACKED_LAYOUT]: 'TMUX_APPLY_STACKED_LAYOUT',
    [KIND_TMUX_SPLIT_PANE]: 'TMUX_SPLIT_PANE',
    [KIND_TMUX_FOCUS_PANE]: 'TMUX_FOCUS_PANE',
    [KIND_TMUX_RENAME_PANE]: 'TMUX_RENAME_PANE',
    [KIND_TMUX_MOVE_PANE]: 'TMUX_MOVE_PANE',
    [KIND_TMUX_BREAK_PANE]: 'TMUX_BREAK_PANE',
    [KIND_TERM_INPUT]: 'TERM_INPUT',
    [KIND_TERM_PASTE]: 'TERM_PASTE',
    [KIND_TERM_RESIZE]: 'TERM_RESIZE',
    [KIND_TERM_SYNC_SIZE]: 'TERM_SYNC_SIZE',
    [KIND_TERM_OUTPUT]: 'TERM_OUTPUT',
    [KIND_TERM_HISTORY]: 'TERM_HISTORY',
    [KIND_CLIPBOARD_WRITE]: 'CLIPBOARD_WRITE',
    [KIND_SWITCH_ACK]: 'SWITCH_ACK',
    [KIND_LIVE_RESUME]: 'LIVE_RESUME',
    [KIND_CHUNK]: 'CHUNK',
    [KIND_AGENT_SUBSCRIBE]: 'AGENT_SUBSCRIBE',
    [KIND_AGENT_UNSUBSCRIBE]: 'AGENT_UNSUBSCRIBE',
    [KIND_AGENT_EVENT]: 'AGENT_EVENT',
    [KIND_WATCH_EVENT]: 'WATCH_EVENT',
  };
  return kindMap[kind] ?? `UNKNOWN(0x${kind.toString(16).padStart(4, '0')})`;
}
