// WebSocket Borsh 协议客户端模块

export {
  BorshWebSocketClient,
  defaultWsUrl,
  getBorshClient,
  resetBorshClient,
  type BorshClientOptions,
  type ConnectionState,
  type BorshMessage,
  type MessageHandler,
  type StateChangeHandler,
  type ErrorHandler,
  type ChunkProgress,
  type ChunkProgressHandler,
  type WebSocketLike,
  type SocketFactory,
} from './client';

export {
  createGatewayConnection,
  type GatewayConnection,
  type GatewayConnectionOptions,
} from './connection';

export {
  WebSocketGatewayTransport,
  LazyWebSocketGatewayTransport,
  createSharedGatewayTransport,
  encodeGatewayTransportCommand,
  type GatewayHistoryCursor,
  type GatewayKittyGraphicsMessage,
  type GatewayPaneHistoryPage,
  type GatewayPaneScreenSnapshot,
  type GatewayRebaseReason,
  type GatewayTerminalCursor,
  type GatewayTerminalData,
  type GatewayTransport,
  type GatewayTransportCapabilities,
  type GatewayTransportCommand,
  type GatewayTransportEvent,
  type GatewayTransportSourceRoute,
  type SharedGatewayTransport,
  type SharedGatewayTransportOptions,
} from './transport';

export {
  PaneSinkRegistry,
  getDefaultPaneSinkRegistry,
  type PaneSink,
  type PaneResetOrigin,
} from './pane-sink-registry';

export {
  SelectStateMachine,
  getSelectStateMachine,
  resetSelectStateMachine,
  type SelectTransactionState,
  type SelectTransaction,
  type OutputGateState,
  type OutputGate,
  type SelectStartEvent,
  type SwitchAckEvent,
  type HistoryEvent,
  type LiveResumeEvent,
  type OutputEvent,
  type SelectFailedEvent,
  type SelectEvent,
  type SelectCallbacks,
  type SelectFailureReason,
  type SelectTimerScheduler,
  type SelectStateMachineOptions,
} from './state-machine';

export {
  generateSelectToken,
  buildDeviceConnect,
  buildDeviceDisconnect,
  buildTmuxSelect,
  buildTmuxSelectWindow,
  buildTmuxCreateWindow,
  buildTmuxCloseWindow,
  buildTmuxClosePane,
  buildTmuxRenameWindow,
  buildTmuxSetWindowStyle,
  buildTmuxReorderWindows,
  buildTmuxReorderPanes,
  buildTmuxSubscribePanes,
  buildTmuxFetchPaneHistory,
  buildTmuxResizePane,
  buildTmuxApplyStackedLayout,
  buildTmuxSplitPane,
  buildTmuxFocusPane,
  buildTmuxRenamePane,
  buildTmuxMovePane,
  buildTmuxBreakPane,
  type MovePanePosition,
  buildTermInput,
  buildTermKeyInput,
  buildTermPaste,
  buildTermResize,
  buildTermSyncSize,
  buildAgentSubscribe,
  buildAgentUnsubscribe,
  buildSiteThemeUpdate,
  decodeDeviceConnected,
  decodeDeviceDisconnected,
  decodeDeviceEvent,
  decodeStateSnapshot,
  decodeTmuxEvent,
  decodeTermOutput,
  decodeTermHistory,
  decodeSwitchAck,
  decodeLiveResume,
  decodeError,
  decodeSiteThemeUpdate,
  type TmuxSelectParams,
} from './message-builder';
