#!/usr/bin/env node
/**
 * i18n Build Script
 * 
 * This script runs at build time to:
 * 1. Read all locale JSON files from src/i18n/locales/
 * 2. Merge them into a single resources.ts file
 * 3. Generate type definitions
 * 4. Keep the manifest.json for runtime use
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const LOCALES_DIR = path.join(__dirname, '../src/i18n/locales');
const OUTPUT_FILE = path.join(__dirname, '../src/i18n/resources.ts');

interface LocaleInfo {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
  isDefault: boolean;
}

interface Manifest {
  locales: LocaleInfo[];
  defaultLocale: string;
}

function main() {
  console.log('[i18n] Building resources...');

  // Read manifest
  const manifestPath = path.join(LOCALES_DIR, 'manifest.json');
  const manifest: Manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));

  // Read all locale files
  const resources: Record<string, unknown> = {};
  
  for (const locale of manifest.locales) {
    const filePath = path.join(LOCALES_DIR, `${locale.code}.json`);
    
    if (!fs.existsSync(filePath)) {
      console.warn(`[i18n] Warning: Locale file not found: ${locale.code}.json`);
      continue;
    }

    const content = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    resources[locale.code] = content;
    console.log(`[i18n] Loaded: ${locale.code} (${locale.nativeName})`);
  }

  // Generate TypeScript content
  const tsContent = generateTypeScript(resources, manifest);
  
  // Write output
  fs.writeFileSync(OUTPUT_FILE, tsContent, 'utf-8');
  console.log(`[i18n] Generated: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
  
  // Generate types
  const typesContent = generateTypes(resources, manifest);
  const typesFile = path.join(__dirname, '../src/i18n/types.ts');
  fs.writeFileSync(typesFile, typesContent, 'utf-8');
  console.log(`[i18n] Generated: ${path.relative(process.cwd(), typesFile)}`);

  console.log(`[i18n] Build complete. ${Object.keys(resources).length} locales.`);
}

function generateTypeScript(resources: Record<string, unknown>, manifest: Manifest): string {
  const resourceEntries = Object.entries(resources).map(([code, content]) => {
    return `  ${code}: ${JSON.stringify(content, null, 2)} as const`;
  }).join(',\n');

  return `// Auto-generated by scripts/build-i18n.ts
// Do not edit this file directly. Edit JSON files in locales/ instead.

import type { Manifest } from './types.js';

export const I18N_RESOURCES = {
${resourceEntries}
} as const;

export type I18nResources = typeof I18N_RESOURCES;
export type LocaleCode = keyof I18nResources;

export const DEFAULT_LOCALE: LocaleCode = '${manifest.defaultLocale}';

export const I18N_MANIFEST: Manifest = ${JSON.stringify(manifest, null, 2)} as const;

export function toBCP47(locale: LocaleCode): string {
  return locale.replace('_', '-');
}

export const AVAILABLE_LOCALES: LocaleCode[] = ${JSON.stringify(Object.keys(resources))};
`;
}

function generateTypes(resources: Record<string, unknown>, manifest: Manifest): string {
  // Extract nested keys from the first locale for type definitions
  const firstLocale = Object.values(resources)[0] as Record<string, unknown>;
  
  function extractKeys(obj: unknown, prefix = ''): string[] {
    if (typeof obj !== 'object' || obj === null) return [];
    
    const keys: string[] = [];
    for (const [key, value] of Object.entries(obj)) {
      const fullKey = prefix ? `${prefix}.${key}` : key;
      keys.push(fullKey);
      
      if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
        keys.push(...extractKeys(value, fullKey));
      }
    }
    return keys;
  }

  const translationKeys = extractKeys(firstLocale?.translation);
  
  return `// Auto-generated by scripts/build-i18n.ts
// Do not edit this file directly.

export interface LocaleInfo {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
  isDefault: boolean;
}

export interface Manifest {
  locales: LocaleInfo[];
  defaultLocale: string;
}

export type TranslationKey =
${translationKeys.map(k => `  | '${k}'`).join('\n')};
`;
}

main();
